### ISSUE TITLE
bootstrap missing

### ISSUE THREAD

**Issue by ghost** [SiddAjmera/MovieChatbotUsingAngularMaterial#1]
ng serve said missing bootstrap. needed to run following:
npm install bootstrap@4.0.0-alpha.6

**Comment by SiddAjmera** [comment]
@yuantw , thanks a lot for pointing that out. [This commit](https://github.com/SiddAjmera/MovieChatbotUsingAngularMaterial/commit/0a8f279b3f8e8adbc57ddaa4655bab1ebedc11e4) should fix it.

**Comment by SiddAjmera** [comment]
Fixed with [f278986](https://github.com/SiddAjmera/MovieChatbotUsingAngularMaterial/commit/0a8f279b3f8e8adbc57ddaa4655bab1ebedc11e4)
